---
# tasks file for skbox-service
- hosts: all
  become: true

- name: Pull Docker image
      docker_image:
        name: "{{ container_image }}"
        source: pull

- name: Create Unit file
  template: 
    src=skbox.service.j2 dest=/etc/systemd/system/skbox.service 
    mode=644
  notify:
    - reload systemctl
- name: Start service
  service: 
    name=skbox.service 
    state=started 
    enabled=yes